"""Appendix table behind the 63% figure of the main text (0926).

Reads the data JSON saved by fig_harness_result.py next to fig_scislopharness_result.pdf and writes
tables/supp_tables/tab_harness_gap.tex. For every measure the entry is the mean score after round 3
minus the matched human mean (the same quantity the figure plots), and the last row sums the absolute
distances over the six measures. The main text's 63% is 1 - sum(ours) / sum(Claude Code).

Usage: python tab_harness_gap.py <paper dir>   (paper dir holds figures/main_figures and tables/supp_tables)
"""
import json, sys
from pathlib import Path

paper = Path(sys.argv[1] if len(sys.argv) > 1 else '.')
src = paper / 'figures/main_figures/fig_scislopharness_result_data.json'
dst = paper / 'tables/supp_tables/tab_harness_gap.tex'
d = json.load(open(src))
S, hm = d['series'], d['human_mean']

ITEMS = [('macro_redund', 'Macro redundancy'), ('xsec_ref', 'Cross-section refs.'), ('argument_graph', 'Argument graph'),
         ('citation', 'Citation isolation'), ('fig_exposition', 'Figure exposition'), ('evidence_gap', 'Evidence gap')]
ARMS = ['a1_base', 'a2_code', 'a3_review', 'a4_slop', 'ours']
R = 3

def gap(item, arm, r):
    return S[item][arm][r][0] - hm[item]

def fmt(v, bold=False):
    sign = '-' if v < 0 else '+'
    if bold:
        return r'\textbf{$\boldsymbol{%s}$%.3f}' % (sign, abs(v))
    return '$%s$%.3f' % (sign, abs(v))

lines = []
lines.append(r'\begin{table}[!ht]')
lines.append(r'\centering\small')
lines.append(r'\renewcommand{\arraystretch}{1.12}')
lines.append(r'\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}')
lines.append(r'\setlength{\tabcolsep}{4pt}')
lines.append(r'\begin{tabular}{@{}l r rrrr >{\columncolor{oursbg}}r@{}}')
lines.append(r'\toprule')
lines.append(r'\headrow Measure & Original & Base prompting & Claude Code & Reviewer-based & Slop-aware & \MitigateName \\')
lines.append(r'\midrule')
sums = {a: 0.0 for a in ARMS}; sum0 = 0.0
for key, name in ITEMS:
    g0 = gap(key, 'ours', 0); sum0 += abs(g0)
    gs = {a: gap(key, a, R) for a in ARMS}
    best = min(ARMS, key=lambda a: abs(gs[a]))
    for a in ARMS: sums[a] += abs(gs[a])
    cells = [fmt(g0)] + [fmt(gs[a], a == best) for a in ARMS]
    lines.append('%s & %s \\\\' % (name, ' & '.join(cells)))
lines.append(r'\midrule')
best = min(ARMS, key=lambda a: sums[a])
cells = ['%.3f' % sum0] + [(r'\textbf{%.3f}' if a == best else '%.3f') % sums[a] for a in ARMS]
lines.append(r'Sum of absolute distances & %s \\' % ' & '.join(cells))
lines.append(r'\bottomrule')
lines.append(r'\end{tabular}')
lines.append(r'\caption{Distance from the matched human mean after the third revision round for each measure, and its sum over the six measures, on the %d papers of Figure~\ref{fig:SciSlopHarness_result}. Each entry is the mean score of the revised papers minus the human mean, so a negative value lies below the human mean, and bold marks the smallest distance in each row.}' % d['n'])
lines.append(r'\label{tab:harness_gap}')
lines.append(r'\end{table}')

header = ('% Generated by paper/draft_v6/slopharness/ver1/api/code/tab_harness_gap.py from\n'
          '% figures/main_figures/fig_scislopharness_result_data.json (the data behind Fig. fig:SciSlopHarness_result).\n'
          '% Entry = mean score after round 3 minus matched human mean. Do not edit by hand.\n')
dst.write_text(header + '\n'.join(lines) + '\n')
red = 1 - sums['ours'] / sums['a2_code']
print('wrote', dst)
print('sum |gap| R3:', {a: round(v, 3) for a, v in sums.items()}, '| original', round(sum0, 3))
print('reduction vs Claude Code: %.1f%%  | closure vs original: %.1f%%' % (100 * red, 100 * (1 - sums['ours'] / sum0)))
