r"""Appendix table for app:measurers_review: rejected-against-accepted AUROC inside each ICLR year,
for every system and every slop measure, from results/scores_years.csv.

Same rule as panel (c) of fig_review_alignment.py: within one year, the probability that a rejected paper scores
more AI-like than an accepted one (accept + oral), every score oriented so that higher means more AI-like, and a cell
is printed only when both sides hold at least 15 papers. The panel draws four of these rows; the table shows all of
them, so each measure's own association can be read (five-measure aggregate row dropped 0924 at the author's request).
Writes $SCISLOP_PAPER_DIR/tables/supp_tables/tab_review_year_auroc.tex and results/alignment/year_auroc_table.json.
"""
import csv, itertools, json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.environ.get("SCISLOP_ROOT", ".")
OUT_TEX = os.environ.get("SCISLOP_PAPER_DIR", ".") + "/tables/supp_tables/tab_review_year_auroc.tex"
OUT_JSON = f"{HERE}/results/alignment/year_auroc_table.json"
YEARS = [str(y) for y in range(2017, 2026)]
MIN_SIDE = 15
ROWS = [  # key, label, AI direction
    ("binoculars", "Binoculars", -1), ("detectgpt", "DetectGPT", +1), ("nts", "NTS", +1),
    ("rev_b2h", "CycleReviewer", -1), ("rev_b3a", "AI Scientist", -1),
    ("agg3", r"\textbf{\scislop{} (Fig.~\ref{fig:review_scores})}", +1),
    ("macro_redund", r"\emph{Macro redundancy}", +1), ("xsec_ref", r"\emph{Cross-section references}", +1),
    ("argument_graph", r"\emph{Argument graph}", +1), ("citation", r"\emph{Citation isolation}", +1),
    ("fig_exposition", r"\emph{Figure exposition}", +1), ("evidence_gap", r"\emph{Evidence gap}", +1),
]
rows = [r for r in csv.DictReader(open(f"{HERE}/results/scores_years.csv")) if r["group"] in ("reject", "accept", "oral")]
num = lambda r, c: None if r.get(c) in (None, "", "None") else float(r[c])
auroc = lambda p, n: sum(1.0 if a > b else 0.5 if a == b else 0.0 for a, b in itertools.product(p, n)) / (len(p) * len(n))

table, counts = {}, {}
for y in YEARS:
    rej = [r for r in rows if r["year"] == y and r["group"] == "reject"]
    acc = [r for r in rows if r["year"] == y and r["group"] in ("accept", "oral")]
    counts[y] = (len(rej), len(acc))
for k, lab, d in ROWS:
    table[k] = {}
    for y in YEARS:
        rej = [num(r, k) * d for r in rows if r["year"] == y and r["group"] == "reject" and num(r, k) is not None]
        acc = [num(r, k) * d for r in rows if r["year"] == y and r["group"] in ("accept", "oral") and num(r, k) is not None]
        table[k][y] = round(auroc(rej, acc), 3) if len(rej) >= MIN_SIDE and len(acc) >= MIN_SIDE else None

def cell(v):
    if v is None:
        return r"\nores"
    s = f"{v:.3f}"
    return s if v > 0.5 else r"\textcolor{black!55}{" + s + "}"

lines = [
    "% Generated by paper/draft_v6/review/scripts/table_review_year_auroc.py from results/scores_years.csv (0924).",
    "% Rejected-against-accepted AUROC inside each ICLR year; a cell needs 15 papers a side. Gray = at or below chance.",
    r"\begin{table}[ht]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{2.6pt}", r"\renewcommand{\arraystretch}{1.12}",
    r"\begin{tabular}{@{}l" + "r" * len(YEARS) + r" c@{}}", r"\toprule",
    "System & " + " & ".join(YEARS) + r" & $>0.5$ \\",
    r"\midrule",
    r"Rejected / accepted papers & " + " & ".join(f"{a}/{b}" for a, b in counts.values()) + r" & \\",
    r"\midrule",
]
groups = [("AI text detectors", ["binoculars", "detectgpt", "nts"]), ("Automated reviewers", ["rev_b2h", "rev_b3a"]),
          ("Slop aggregate", ["agg3"]),
          ("Single measures", ["macro_redund", "xsec_ref", "argument_graph", "citation", "fig_exposition", "evidence_gap"])]
LAB = {k: lab for k, lab, _ in ROWS}
summary = {}
for gname, keys in groups:
    lines.append(r"\multicolumn{" + str(len(YEARS) + 2) + r"}{@{}l}{\textit{" + gname + r"}} \\")
    for k in keys:
        vals = [table[k][y] for y in YEARS]
        have = [v for v in vals if v is not None]
        above = sum(1 for v in have if v > 0.5)
        summary[k] = {"above": above, "of": len(have), "below_or_equal": len(have) - above,
                      "min": min(have) if have else None, "max": max(have) if have else None}
        lines.append(r"\hspace{0.6em}" + LAB[k] + " & " + " & ".join(cell(v) for v in vals) + f" & {above}/{len(have)}" + r" \\")
    if gname != groups[-1][0]:
        lines.append(r"\addlinespace[2pt]")
lines += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Rejection AUROC inside each ICLR year for every system and measure of this paper, with the number of years above chance in the last column, counted over the years that hold a value. "
          r"A value is the probability that a rejected paper of that year scores more AI-like than an accepted one, 0.5 is chance, gray marks a value at or below it, and a dash marks a year with fewer than 15 papers on one side.}",
          r"\label{tab:review_year_auroc}", r"\end{table}"]
os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
open(OUT_TEX, "w").write("\n".join(lines) + "\n")
json.dump({"counts": counts, "auroc": table, "summary": summary}, open(OUT_JSON, "w"), indent=1)
print(f"wrote {OUT_TEX}")
for k, s in summary.items():
    print(f"  {k:16s} above {s['above']}/{s['of']}  min {s['min']}  max {s['max']}")
